PROJECT_ROOT=../../..
CSOURCES=stdio_funcs.c string.c msgd.c unistd.c
ASMSOURCES=system.s stdio_params.s

all: asmsources csources

include ../directives.mk
include ../csources.mk
include ../asmsources.mk
include ../builddir.mk

