PROJECT_ROOT=../../..
CSOURCES=$(wildcard *.c)
CPPSOURCES=$(wildcard *.cpp)
ASMSOURCES=$(wildcard *.s)

all: asmsources csources cppsources

include ../directives.mk
include ../csources.mk
include ../cppsources.mk
include ../asmsources.mk
include ../builddir.mk

