PROJECT_ROOT=../../..
CPPFLAGS=
CPPSOURCES=main.cpp
ASMSOURCES=entry.s

all: asmsources cppsources

include ../directives.mk
include ../asmsources.mk
include ../cppsources.mk

build:
	mkdir build

clean:
	rm -rf build
  
